Player Dashboard: List of Assigned Quests
nbcp/firestarter-leaderboard pull request #19
Opened 2019-02-28 03:30 UTC by aronpadolina

Initial Commit

2019-02-28 04:46 UTC, ben-x-dev requested changes
please fix lint and build errors

2019-02-28 04:46 UTC, nbcp commented on src/app/ui/player-quest-list/submit-quest-dialog.component.ts
> +      completionProof: new FormControl('', [Validators.required, Validators.pattern(this.urlPatternRegex)]])
compile error here because of double `]`

2019-02-28 04:46 UTC, nbcp commented on src/app/ui/player-quest-list/player-quest-list.component.ts
> +            this.emailService.sendEmail(playerQuest.teamLeadEmail,
you need to add `teamLeadEmail` property under `PlayerQuest` interface in player-quest.d.ts

2019-02-28 04:46 UTC, nbcp commented on src/app/ui/player-quest-list/player-quest-list.component.ts
> +            this.emailService.sendEmail(playerQuest.teamLeadEmail,
also `sendEmail()` method is an observable hence you need to append subscribe to it then place notifyServiceUpdate inside that to ensure success

2019-02-28 04:51 UTC, nbcp commented
please also remove `package-lock.json` from the commit, we don't need to update it unless we have changes in `package.json`

2019-02-28 06:21 UTC, aronpadolina commented
Done with all the lint and build errors

2019-02-28 13:19 UTC, ben-x-dev requested changes
Just 1 last thing, please return the `package-lock.json` file, we need that.
what i meant earlier is to just remove changes there from your commit.

2019-03-01 06:13 UTC, ben-x-dev approved these changes

2019-03-01 06:13 UTC, merged

2019-03-04 02:16 UTC, nbcp commented
closes #6