EXP and Ranks
nbcp/firestarter-leaderboard pull request #42
Opened 2019-03-13 07:38 UTC by fjgallard

- User Profile XP
- Season XP and Rank on Tables
- Colors on EXP on tables

2019-03-13 07:41 UTC, fjgallard commented
This closes #33

2019-03-13 08:19 UTC, ben-x-dev requested changes

2019-03-13 08:19 UTC, nbcp commented on src/app/players/playerpoints.service.ts
> +
you'll need another method here to query all points of all team members using `where('teamId', '==', teamId)` instead of playerId

2019-03-13 08:19 UTC, nbcp commented on src/app/ui/team-page/team-members/team-members.component.ts
> +        this.members$ = members.map(this.getMemberInfo.bind(this));
suggest to have here the new method above and do somethin like:
```javascript
const memberPoints$ = this.teamsService.getTeamMembers(this.currentUser.membership.teamId);
combineLatest(teamMembers$, memberPoints$).pipe(
  map(([members, points]) =>{
    members.map((member) => ({ 
      ...member, 
      points: points.find((point) => point.playerId === member.playerId).totalPoints
    })
  })
);
```

2019-03-14 10:47 UTC, nbcp commented on src/app/ui/player-quest-list/player-quest-list.component.html
> +      [ngStyle]="{'color': quest.completed ? 'green' : 'red' }"
no longer need this, ngClass below already handles the color changes in XP

2019-03-14 10:47 UTC, nbcp commented on src/app/players/playerpoints.d.ts
> +interface PlayerPoint {
please use PlayerPoints in `player-points.d.ts` instead

2019-03-14 10:47 UTC, nbcp commented on src/app/players/playerpoints.service.ts
> +      map((playerPoint: PlayerPoint) => playerPoint ? playerPoint.totalPoints : null)
please follow the return type and return `0` instead of `null`

2019-03-14 10:47 UTC, nbcp commented on src/app/core/auth.service.ts
> +    totalExp$.subscribe(exp => console.log(exp));
why?

2019-03-14 11:46 UTC, ben-x-dev approved these changes

2019-03-14 12:02 UTC, merged